### PR TITLE
Add release variant that operates on push event

### PR DESCRIPTION
**Pull request by iku000888**
I want the release script to operate on master push, so I replicated cmd/release and modified the attribute access to operate on https://developer.github.com/v3/activity/events/types/#pushevent

### CODE REVIEW

**Comment by rojopolis** [comment]
Can't we just have one script that handles both cases?

**Comment by iku000888** [comment]
Probably. But would be beyond my python capacities :sweat_smile:

**Comment by rojopolis** [comment]
> Probably. But would be beyond my python capacities 😅

OK, it's fine for now then...  I'll add a ticket in backlog to revisit.  There's a bug in here I need to address sooner or later anyway.

**Comment by iku000888** [comment]
:crossed_fingers:

**Pull request merged**
